export default [
  {
    id: 0,
    name: "Color Museum",
    description: "NFT marketplace for color NFTs",
    image: "images/projects/1.jpg",
    tags: ["NextJS", "ExpressJS", "Blockchain", "PostgreSQL", "Bootstrap"],
    liveview: "https://color.museum",
    github: "/",
    alt: "Ethereum based NFT marketplace project",
  },
  {
    id: 1,
    name: "Iswap",
    description: "CEX site base on Tron Net",
    image: "images/projects/2.jpg",
    tags: ["React", "ExpressJS", "Blockchain", "MySQL","Bootstrap"],
    liveview: "https://intercroneswap.com/#/",
    github: "/",
    alt: "CEX site base on Tron",
  },
  {
    id: 2,
    name: "51 Game",
    description: "Online Multi betting game site",
    image: "images/projects/3.jpg",
    tags: ["React", "Django", "Bootstrap","MongoDB", "Blockchain"],
    liveview: "https://www.51.com/",
    github: "/",
    alt: "This is the online betting game site",
  },
  {
    id: 3,
    name: "One Model Place",
    description: "This is the fashon model site",
    image: "images/projects/4.jpg",
    tags: ["React", "Laravel", "TailwindCSS","MySQL"],
    liveview: "https://www.onemodelplace.com/",
    github: "/",
    alt: "Popular model site",
  },
  {
    id: 4,
    name: "Chewy",
    description:
      "Online shopping site for buying various animal foods",
    image: "images/projects/5.jpg",
    tags: ["React", "Laravel", "Bootstrap", "MongoDB"],
    liveview: "https://www.chewy.com/",
    github: "/",
    alt: "Online animal food shop",
  },
];
